<Project>
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <DefaultTargetFramework>net7.0</DefaultTargetFramework>
    <LtsTargetFramework>netstandard2.0</LtsTargetFramework>
    <TargetFramework Condition=" $(MSBuildProjectName.Contains('Windows')) ">net48</TargetFramework>
    <TargetFramework Condition=" '$(TargetFramework)' == '' and '$(TargetFrameworks)' == '' ">$(DefaultTargetFramework)</TargetFramework>
    <Features>strict</Features>
    <Deterministic>True</Deterministic>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>4.4.0</Version>
    <PackageVersion>4.4.0-icore</PackageVersion>
    <AvaloniaEditVersion>0.10.12.2</AvaloniaEditVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>Enable</Nullable>
    <IsPackable>false</IsPackable>
    <Authors>Eli Arbel</Authors>
    <PackageProjectUrl>https://github.com/aelij/RoslynPad</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageTags>Roslyn;RoslynPad</PackageTags>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
  </PropertyGroup>
</Project>
