<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(LtsTargetFramework)</TargetFramework>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <!-- iCore fork: System.Text.Json is not inbox on netstandard2.0. -->
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Themes\*.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Themes\*.json" />
    <Content Include="Themes\*.json" Exclude="Themes\vs2019*.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
